version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - crypto-net

  backend:
    build: .
    container_name: crypto_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - crypto-net

volumes:
  pgdata:


networks:
  crypto-net:
